import Link from 'next/link';
import { ArrowRight, BookOpen, FlaskConical, Scale, ClipboardCheck } from 'lucide-react';

const steps = [
  { icon: BookOpen, title: '1. Make a small experiment journal', text: 'Start from a template or write one question. Add what you are testing and what would make the result less trustworthy.', href: '/experiments', action: 'Open Experiment Journal' },
  { icon: FlaskConical, title: '2. Run a local model', text: 'Use Qwen through Ollama for the stronger local path, or use the Python/Transformers path for a small controlled open-model check. The prompt and completion are both preserved.', href: '/lab', action: 'Open Data Lab' },
  { icon: Scale, title: '3. Compare matching responses', text: 'Run two models on the exact same prompt. Then review the pair in Annotation Studio. SYNTH does not allow a mismatched or simulator pair to become preference training data.', href: '/annotate', action: 'Open Annotation Studio' },
  { icon: ClipboardCheck, title: '4. Review the dataset before export', text: 'Dataset Review shows what is truly eligible for a later training attempt and sends packet records through the local Python structural preflight.', href: '/datasets', action: 'Open Dataset Review' },
];

export default function OnboardingPage() {
  return <main className="min-h-screen bg-background text-foreground"><div className="max-w-4xl mx-auto px-6 py-14 space-y-10"><div><p className="text-xs font-mono text-[#C4956A] uppercase tracking-widest">SYNTH local-first setup</p><h1 className="text-4xl font-bold mt-3">START WITH ONE REAL QUESTION</h1><p className="text-muted-foreground text-sm leading-relaxed mt-4 max-w-2xl">SYNTH is not a button that magically improves a model. It is the place where you make a small experiment, keep the evidence together, add your judgment, and export only the data that is worth reviewing again.</p></div><div className="grid grid-cols-1 md:grid-cols-2 gap-5">{steps.map((step) => { const Icon = step.icon; return <Link key={step.title} href={step.href} className="rounded-xl border border-border/60 bg-card/50 p-5 hover:border-[#C4956A]/50 transition-colors"><Icon className="w-5 h-5 text-[#C4956A]"/><h2 className="text-sm font-semibold mt-3">{step.title}</h2><p className="text-xs text-muted-foreground leading-relaxed mt-2">{step.text}</p><span className="inline-flex items-center gap-1 text-xs text-[#C4956A] mt-4">{step.action}<ArrowRight className="w-3.5 h-3.5"/></span></Link>; })}</div><section className="rounded-xl border border-[#C4956A]/30 bg-[#C4956A]/5 p-5"><h2 className="text-sm font-semibold">The simplest useful first experiment</h2><p className="text-xs text-muted-foreground mt-2 leading-relaxed">Ask Qwen and SmolLM the same narrow question. Do not ask which answer sounds smarter. Check whether they followed the instruction, named assumptions, showed uncertainty where it mattered, and avoided making up facts. Write down why you chose one, or why neither earned a choice.</p></section></div></main>;
}
